version: '3.8'
services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - APP_DB_HOST=db
      - APP_DB_PORT=3306
      - APP_DB_NAME=tj_start
      - APP_DB_USER=root
      - APP_DB_PASSWD=my-secret-pw
      - COOKIE_DOMAIN=localhost
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=tj_start
    ports:
      - "3306:3306"


